// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr7lEoPMZHq1E15BbZEosgevwKAuP6iE4',
    appId: '1:1000008219906:web:0fc02e968a9c3b868ad61b',
    messagingSenderId: '1000008219906',
    projectId: 'fir-cli-c3269',
    authDomain: 'fir-cli-c3269.firebaseapp.com',
    storageBucket: 'fir-cli-c3269.firebasestorage.app',
    measurementId: 'G-VLRV6JVJ7F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6RbykhQPUzLYIAcxCMdFXvLmXP2NqVPM',
    appId: '1:1000008219906:android:c2a83363b6d9ada48ad61b',
    messagingSenderId: '1000008219906',
    projectId: 'fir-cli-c3269',
    storageBucket: 'fir-cli-c3269.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASG3Uaj7BQhyghDLlXPrHEndVJuHpZlYQ',
    appId: '1:1000008219906:ios:00becc18e13fba338ad61b',
    messagingSenderId: '1000008219906',
    projectId: 'fir-cli-c3269',
    storageBucket: 'fir-cli-c3269.firebasestorage.app',
    iosBundleId: 'com.example.p',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASG3Uaj7BQhyghDLlXPrHEndVJuHpZlYQ',
    appId: '1:1000008219906:ios:00becc18e13fba338ad61b',
    messagingSenderId: '1000008219906',
    projectId: 'fir-cli-c3269',
    storageBucket: 'fir-cli-c3269.firebasestorage.app',
    iosBundleId: 'com.example.p',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBr7lEoPMZHq1E15BbZEosgevwKAuP6iE4',
    appId: '1:1000008219906:web:a614a0eb51dfa9458ad61b',
    messagingSenderId: '1000008219906',
    projectId: 'fir-cli-c3269',
    authDomain: 'fir-cli-c3269.firebaseapp.com',
    storageBucket: 'fir-cli-c3269.firebasestorage.app',
    measurementId: 'G-Z4QP64BZDB',
  );
}
